<a href="https://colab.research.google.com/github/subodh3788/Electricity-Demand-Prediction/blob/main/historicalData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%pip install meteostat
import requests
import numpy as np
import pandas as pd
from datetime import datetime
import json
from meteostat import Point, Daily
import ssl
ssl._create_default_https_context=ssl._create_unverified_context

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting meteostat
  Downloading meteostat-1.6.2-py3-none-any.whl (31 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from meteostat) (1.21.6)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from meteostat) (2022.1)
Requirement already satisfied: pandas>=1.1 in /usr/local/lib/python3.7/dist-packages (from meteostat) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1->meteostat) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1->meteostat) (1.15.0)
Installing collected packages: meteostat
Successfully installed meteostat-1.6.2

In [3]:
# Set time period
start = datetime(2019, 1, 1)
end = datetime(2022, 6, 25)

# Create Point for location
LongIsland = Point(40.7891, -73.1350)

# Get daily data
data = Daily(LongIsland, start, end)
HistData = data.fetch()

In [4]:
HistData.drop(['tmin','tmax','snow','wdir','wpgt','pres','tsun'],inplace=True,axis=1)
HistData.rename(columns={'tavg':'Temperature','prcp':'rain','wspd':'windSpeed'},inplace=True)
HistData=HistData[['Temperature','windSpeed','rain']]
HistData.rename_axis('date')

            Temperature  windSpeed  rain
date
2019-01-01         10.6       24.8   6.4
2019-01-02          2.7        9.4   0.0
2019-01-03          4.9       13.0   0.0
2019-01-04          2.0       10.8   0.0
2019-01-05          6.6       16.2  12.4
...                 ...        ...   ...
2022-06-21         20.4        7.6   0.3
2022-06-22         16.8       11.9  15.4
2022-06-23         19.2       14.2   0.1
2022-06-24         19.5       10.9   0.3
2022-06-25         22.5        8.5   0.0

[1272 rows x 3 columns]