<a href="https://colab.research.google.com/github/subodh3788/Electricity-Demand-Prediction/blob/main/WeatherForecastData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests
import numpy as np
import pandas as pd
from datetime import datetime
import json
import ssl
ssl._create_default_https_context=ssl._create_unverified_context

In [11]:
df_forecast=pd.DataFrame()
response=requests.get('https://api.weather.gov/gridpoints/OKX/61,42/forecast').json()

In [12]:
weWant=response['properties']['periods']
startTime=[]
date=[]
Temperature=[]
windSpeed=[]
rain=[]
for i in range(len(weWant)):
    startTime.append(weWant[i]['startTime'])
    date.append(weWant[i]['endTime'])
    Temperature.append(weWant[i]['temperature'])
    windSpeed.append(weWant[i]['windSpeed'])
    rain.append(weWant[i]['detailedForecast'])

In [13]:
df_forecast['date']=date
df_forecast['Temperature']=Temperature
df_forecast['wspd']=windSpeed
df_forecast['rain']=rain
df_forecast['date']=pd.to_datetime(df_forecast['date'])
df_forecast['date'] = df_forecast['date'].dt.date
df_forecast

,date,Temperature,wspd,rain
0,2022-06-27,68,14 mph,"Mostly cloudy, with a low around 68. Southwest..."
1,2022-06-27,76,9 to 14 mph,"A slight chance of rain showers before 9am, th..."
2,2022-06-28,60,2 to 8 mph,A chance of rain showers before midnight. Most...
3,2022-06-28,78,7 mph,"Mostly sunny. High near 78, with temperatures ..."
4,2022-06-29,61,1 to 6 mph,"Partly cloudy, with a low around 61. Southwest..."
5,2022-06-29,80,1 to 10 mph,"Sunny. High near 80, with temperatures falling..."
6,2022-06-30,63,3 to 10 mph,"Mostly clear, with a low around 63."
7,2022-06-30,83,3 to 9 mph,"Sunny, with a high near 83."
8,2022-07-01,65,5 to 9 mph,"Mostly clear, with a low around 65."
9,2022-07-01,83,5 to 16 mph,"Mostly sunny, with a high near 83."
10,2022-07-02,68,12 to 16 mph,"Partly cloudy, with a low around 68."
11,2022-07-02,84,12 to 16 mph,A chance of showers and thunderstorms after 8a...
12,2022-07-03,67,6 to 14 mph,Showers and thunderstorms likely. Mostly cloud...
13,2022-07-03,81,8 mph,A chance of showers and thunderstorms. Partly ...

In [14]:
df_forecast['windSpeed']=df_forecast['wspd'].astype('str').str.extract('(\d+)').astype(int)
df_forecast['rain_copy']=df_forecast['rain'].astype('str').str.extract('(\d+)%')
df_forecast['rain_copy']=df_forecast['rain_copy'].fillna(0).astype(int)

In [15]:
df_forecast.drop(['rain'],inplace=True,axis=1)
df_forecast.drop(['wspd'],inplace=True,axis=1)

In [16]:
df_forecast.rename(columns={'rain_copy':'rain'},inplace=True)

In [17]:
df_forecast.set_index('date',inplace=True)
df_forecast

            Temperature  windSpeed  rain
date
2022-06-27           68         14     0
2022-06-27           76          9    80
2022-06-28           60          2    50
2022-06-28           78          7     0
2022-06-29           61          1     0
2022-06-29           80          1     0
2022-06-30           63          3     0
2022-06-30           83          3     0
2022-07-01           65          5     0
2022-07-01           83          5     0
2022-07-02           68         12     0
2022-07-02           84         12    40
2022-07-03           67          6    60
2022-07-03           81          8    50